# Pipeline for Nebula Logger
name: Deployment

on:
    push:
        paths-ignore:
            - 'content/**'
            - 'docs/**'
            - 'examples/**'
            - 'packages/**'
            - '.forceignore'
            - '.gitignore'
            - '.prettierignore'
            - '.prettierrc'
            - 'Contributing.md'
            - 'LICENSE'
            - 'package.json'
            - 'README.md'
            - './**/README.md'
            - 'sfdx-project.json'
    pull_request:
        types: [opened, synchronize, reopened]
        paths-ignore:
            - 'content/**'
            - 'docs/**'
            - 'examples/**'
            - 'packages/**'
            - '.forceignore'
            - '.gitignore'
            - '.prettierignore'
            - '.prettierrc'
            - 'Contributing.md'
            - 'LICENSE'
            - 'package.json'
            - 'README.md'
            - './**/README.md'
            - 'sfdx-project.json'

jobs:
    commit-something:
        name: 'LWC Tests'
        runs-on: ubuntu-latest
        environment: Test
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            - name: 'Create and commit a file'
              run: |
                  git config --local user.email "test@github.com"
                  git config --local user.name "GitHub Action test"
                  echo "Hello, world" >> someFile.txt
                  git add someFile.txt
                  git commit -m "Add changes"
                  git push
